### ISSUE TITLE
[Windows] In atom 181 the plugin opens strange locations for the project root

### ISSUE THREAD

**Issue by ericwooley** [danielmahon/atom-open-last-project#25]
All files are remembered but the tree view either loads C:\windows\system32 (i think) or "C:\Users\<user>\AppData\Local\atom\app-0.181.0"

It relates to this issue in atom.
https://github.com/atom/atom/issues/5617

**Comment by steelbrain** [comment]
This has been fixed by #22

**Comment by danielmahon** [comment]
@ericwooley what @steelbrain said ;)... I just published the update

**Comment by SethG911** [comment]
I am still having this issue with Atom 0.181.0 and Open-Last-Project 0.3.1.

**Comment by steelbrain** [comment]
@SethG911 , Can you try this method and see if it works for You? https://github.com/danielmahon/atom-open-last-project/issues/28#issuecomment-75347726
